// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrqw7rNYec6riCudppYjkApFZ7CmYP2g',
    appId: '1:1024442161788:web:4296081560d92e250747f9',
    messagingSenderId: '1024442161788',
    projectId: 'tripmaster-c7210',
    authDomain: 'tripmaster-c7210.firebaseapp.com',
    storageBucket: 'tripmaster-c7210.firebasestorage.app',
    measurementId: 'G-KZDHYSKWS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTkbWjIKzLn_4H5bH68uaJsezA4XVumfI',
    appId: '1:1024442161788:android:6de579a15a506ca00747f9',
    messagingSenderId: '1024442161788',
    projectId: 'tripmaster-c7210',
    storageBucket: 'tripmaster-c7210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1PpjfHP0-Z6tETl1Cfe-BdIP6IYQLE0',
    appId: '1:1024442161788:ios:1ff309ed9572a3730747f9',
    messagingSenderId: '1024442161788',
    projectId: 'tripmaster-c7210',
    storageBucket: 'tripmaster-c7210.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1PpjfHP0-Z6tETl1Cfe-BdIP6IYQLE0',
    appId: '1:1024442161788:ios:1ff309ed9572a3730747f9',
    messagingSenderId: '1024442161788',
    projectId: 'tripmaster-c7210',
    storageBucket: 'tripmaster-c7210.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfrqw7rNYec6riCudppYjkApFZ7CmYP2g',
    appId: '1:1024442161788:web:d12ff05f5bcea79b0747f9',
    messagingSenderId: '1024442161788',
    projectId: 'tripmaster-c7210',
    authDomain: 'tripmaster-c7210.firebaseapp.com',
    storageBucket: 'tripmaster-c7210.firebasestorage.app',
    measurementId: 'G-PP10FK03R0',
  );
}
